"""Read and reconstruct full TPNN histories for offline-RL rollouts.

The stored history for an anchor transition ``i`` is deliberately
``x[episode_start:i]``.  It never contains ``x[i]`` because the current action
must be generated by the RL policy, not copied from the offline behavior
policy.
"""

from pathlib import Path
from typing import Mapping, Optional, Sequence, Tuple, Union

import h5py
import numpy as np


DEFAULT_TPNN_DATA_DIR = Path(
    "/data/datasets/"
    "noshape_gas_benchmark_synthesized_dymodel_all_filter_TPNN"
)
RL_DATA_FILENAME = "rl_data.h5"


class TPNNHistoryStore:
    """In-memory raw token bank plus compact offline-history metadata."""

    def __init__(
        self,
        data_path: Union[str, Path] = DEFAULT_TPNN_DATA_DIR,
        load_chunk_size: int = 65536,
    ) -> None:
        path = Path(data_path).expanduser()
        self.rl_data_path = (
            path / RL_DATA_FILENAME if path.is_dir() else path
        ).resolve()
        if not self.rl_data_path.is_file():
            raise FileNotFoundError(
                f"TPNN rl_data.h5 does not exist: {self.rl_data_path}"
            )
        if load_chunk_size < 1:
            raise ValueError("load_chunk_size must be positive.")

        with h5py.File(self.rl_data_path, "r") as hdf:
            self._validate_hdf(hdf)
            self.history_start_indices = np.asarray(
                hdf["history_start_indices"][:], dtype=np.int64
            )
            self.history_lengths = np.asarray(
                hdf["history_lengths"][:], dtype=np.int64
            )
            self.episode_start_indices = np.asarray(
                hdf["episode_start_indices"][:], dtype=np.int64
            )
            self.episode_end_indices = np.asarray(
                hdf["episode_end_indices"][:], dtype=np.int64
            )
            self.time_steps = np.asarray(hdf["time_step"][:], dtype=np.int64)
            self.terminals = np.asarray(hdf["terminals"][:], dtype=np.bool_)
            self.traj_start_indices = np.asarray(
                hdf["traj_start_indices"][:], dtype=np.int64
            )

            self.num_transitions = int(hdf["observations"].shape[0])
            self.observation_dim = int(hdf["observations"].shape[-1])
            self.pre_action_dim = int(hdf["pre_actions"].shape[-1])
            self.action_dim = int(hdf["actions"].shape[-1])
            if self.pre_action_dim != self.action_dim:
                raise ValueError(
                    f"pre_action_dim={self.pre_action_dim} does not match "
                    f"action_dim={self.action_dim}."
                )
            self.input_dim = (
                self.observation_dim
                + self.pre_action_dim
                + self.action_dim
            )
            self.output_dim = int(hdf.attrs["history_output_dim"])
            self.block_size = int(hdf.attrs["tpnn_block_size"])
            self.max_sequence_length = int(
                hdf.attrs["max_sequence_length"]
            )
            self.source_generator = str(hdf.attrs["source_generator"])
            if self.source_generator != "RPNN":
                raise ValueError(
                    "The offline transition generator must remain RPNN, got "
                    f"{self.source_generator!r}."
                )
            if self.input_dim != int(hdf.attrs["history_input_dim"]):
                raise ValueError(
                    "Computed TPNN input width does not match the HDF5 attrs."
                )

            self.tokens = np.empty(
                (self.num_transitions, self.input_dim), dtype=np.float32
            )
            for start in range(0, self.num_transitions, load_chunk_size):
                end = min(start + load_chunk_size, self.num_transitions)
                observations = np.asarray(
                    hdf["observations"][start:end], dtype=np.float32
                )
                pre_actions = np.asarray(
                    hdf["pre_actions"][start:end], dtype=np.float32
                )
                actions = np.asarray(
                    hdf["actions"][start:end], dtype=np.float32
                )
                self.tokens[start:end, : self.observation_dim] = observations
                pre_start = self.observation_dim
                delta_start = pre_start + self.pre_action_dim
                self.tokens[start:end, pre_start:delta_start] = pre_actions
                self.tokens[start:end, delta_start:] = actions - pre_actions

        self._validate_metadata()

    @staticmethod
    def _validate_hdf(hdf: h5py.File) -> None:
        required_datasets = {
            "observations",
            "pre_actions",
            "actions",
            "terminals",
            "time_step",
            "traj_start_indices",
            "history_start_indices",
            "history_lengths",
            "episode_start_indices",
            "episode_end_indices",
        }
        missing = sorted(required_datasets - set(hdf.keys()))
        if missing:
            raise KeyError(
                f"TPNN rl_data.h5 is missing required datasets: {missing}"
            )
        required_attrs = {
            "history_format",
            "history_includes_current",
            "history_input_layout",
            "history_input_dim",
            "history_output_dim",
            "tpnn_block_size",
            "max_sequence_length",
            "source_generator",
        }
        missing_attrs = sorted(required_attrs - set(hdf.attrs.keys()))
        if missing_attrs:
            raise KeyError(
                f"TPNN rl_data.h5 is missing required attrs: {missing_attrs}"
            )
        if str(hdf.attrs["history_format"]) != "full_raw_history_v1":
            raise ValueError(
                "Unsupported history format: "
                f"{hdf.attrs['history_format']!r}"
            )
        if bool(hdf.attrs["history_includes_current"]):
            raise ValueError(
                "The history store requires histories that exclude the "
                "current transition."
            )
        expected_layout = (
            "observation,pre_action,action_minus_pre_action"
        )
        if str(hdf.attrs["history_input_layout"]) != expected_layout:
            raise ValueError(
                "Unexpected TPNN input layout: "
                f"{hdf.attrs['history_input_layout']!r}"
            )
        if "hidden_states" in hdf:
            raise ValueError(
                "TPNN rl_data.h5 must not contain RPNN hidden_states."
            )

    def _validate_metadata(self) -> None:
        n = self.num_transitions
        one_dimensional = {
            "history_start_indices": self.history_start_indices,
            "history_lengths": self.history_lengths,
            "time_steps": self.time_steps,
            "terminals": self.terminals,
        }
        for name, values in one_dimensional.items():
            if values.shape != (n,):
                raise ValueError(
                    f"{name} has shape {values.shape}; expected {(n,)}."
                )
        transition_indices = np.arange(n, dtype=np.int64)
        if not np.array_equal(
            self.history_start_indices + self.history_lengths,
            transition_indices,
        ):
            raise ValueError(
                "history_start_indices/history_lengths do not end at the "
                "current transition exclusively."
            )
        if not np.array_equal(self.history_lengths, self.time_steps):
            raise ValueError(
                "history_lengths must equal time_step for full histories."
            )
        if np.any(self.history_start_indices < 0):
            raise ValueError("A history starts before transition zero.")
        if np.any(self.history_lengths + 1 > self.block_size):
            raise ValueError(
                "An offline sequence already exceeds the TPNN block size."
            )
        actual_max_sequence_length = int(self.history_lengths.max()) + 1
        if actual_max_sequence_length != self.max_sequence_length:
            raise ValueError(
                f"Stored max_sequence_length={self.max_sequence_length} does "
                f"not match actual value {actual_max_sequence_length}."
            )
        if self.input_dim != int(self.tokens.shape[-1]):
            raise ValueError("The constructed token bank has a wrong width.")
        self.tokens.flags.writeable = False

    def __len__(self) -> int:
        return self.num_transitions

    def validate_anchor_indices(
        self, anchor_indices: Union[np.ndarray, Sequence[int]]
    ) -> np.ndarray:
        anchors = np.asarray(anchor_indices, dtype=np.int64).reshape(-1)
        if anchors.size == 0:
            raise ValueError("At least one rollout anchor is required.")
        if np.any(anchors < 0) or np.any(anchors >= self.num_transitions):
            bad = anchors[
                (anchors < 0) | (anchors >= self.num_transitions)
            ]
            raise IndexError(
                f"Rollout anchors are out of range: {bad[:10].tolist()}"
            )
        return anchors

    def validate_rollout_capacity(
        self,
        anchor_indices: Union[np.ndarray, Sequence[int]],
        rollout_length: int,
        block_size: Optional[int] = None,
    ) -> None:
        """Check ``initial_prefix_length + rollout_length <= block_size``."""
        if rollout_length < 1:
            raise ValueError("rollout_length must be positive.")
        anchors = self.validate_anchor_indices(anchor_indices)
        effective_block_size = (
            self.block_size if block_size is None else int(block_size)
        )
        final_lengths = self.history_lengths[anchors] + rollout_length
        invalid = final_lengths > effective_block_size
        if np.any(invalid):
            bad_anchors = anchors[invalid]
            bad_lengths = final_lengths[invalid]
            raise ValueError(
                "Full TPNN history would exceed block_size="
                f"{effective_block_size}; examples: "
                f"{list(zip(bad_anchors[:10], bad_lengths[:10]))}"
            )

    def offline_prefix(self, anchor_index: int) -> np.ndarray:
        """Return ``x[episode_start:anchor]`` without the current token."""
        anchor = int(
            self.validate_anchor_indices([anchor_index])[0]
        )
        start = int(self.history_start_indices[anchor])
        return self.tokens[start:anchor].copy()

    def build_padded_batch(
        self,
        anchor_indices: Union[np.ndarray, Sequence[int]],
        synthetic_suffixes: np.ndarray,
        current_tokens: np.ndarray,
        block_size: Optional[int] = None,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Build left-aligned variable-length histories for one microbatch.

        Each row is exactly::

            offline_tokens[episode_start:anchor]
            + synthetic_suffix
            + current_synthetic_token

        ``offline_tokens[anchor]`` is never read.
        """
        anchors = self.validate_anchor_indices(anchor_indices)
        current = np.asarray(current_tokens, dtype=np.float32)
        suffixes = np.asarray(synthetic_suffixes, dtype=np.float32)
        batch_size = anchors.shape[0]

        if current.shape != (batch_size, self.input_dim):
            raise ValueError(
                f"current_tokens has shape {current.shape}; expected "
                f"{(batch_size, self.input_dim)}."
            )
        if suffixes.ndim != 3:
            raise ValueError(
                "synthetic_suffixes must have shape [batch, steps, input_dim]."
            )
        if (
            suffixes.shape[0] != batch_size
            or suffixes.shape[2] != self.input_dim
        ):
            raise ValueError(
                f"synthetic_suffixes has shape {suffixes.shape}; expected "
                f"[{batch_size}, steps, {self.input_dim}]."
            )

        suffix_length = int(suffixes.shape[1])
        lengths = (
            self.history_lengths[anchors] + suffix_length + 1
        ).astype(np.int64)
        effective_block_size = (
            self.block_size if block_size is None else int(block_size)
        )
        if np.any(lengths > effective_block_size):
            bad = np.flatnonzero(lengths > effective_block_size)
            raise ValueError(
                "A reconstructed sequence exceeds block_size="
                f"{effective_block_size}; anchors/lengths: "
                f"{[(int(anchors[j]), int(lengths[j])) for j in bad[:10]]}"
            )

        padded = np.zeros(
            (batch_size, int(lengths.max()), self.input_dim),
            dtype=np.float32,
        )
        for row, anchor in enumerate(anchors):
            prefix_start = int(self.history_start_indices[anchor])
            prefix_length = int(self.history_lengths[anchor])
            if prefix_length:
                padded[row, :prefix_length] = self.tokens[
                    prefix_start:anchor
                ]
            if suffix_length:
                suffix_end = prefix_length + suffix_length
                padded[row, prefix_length:suffix_end] = suffixes[row]
            padded[row, lengths[row] - 1] = current[row]
        return padded, lengths

    def validate_offline_data(
        self,
        offline_data: Mapping[str, np.ndarray],
        sample_size: int = 4096,
    ) -> None:
        """Validate that an RL loader and this history file are aligned."""
        required = {
            "full_observations",
            "pre_actions",
            "full_actions",
            "time_step",
            "terminals",
            "traj_start_indices",
        }
        missing = sorted(required - set(offline_data.keys()))
        if missing:
            raise KeyError(
                f"offline_data is missing TPNN alignment keys: {missing}"
            )
        n = int(np.asarray(offline_data["full_observations"]).shape[0])
        if n != self.num_transitions:
            raise ValueError(
                f"offline_data has {n} transitions but the history store has "
                f"{self.num_transitions}."
            )
        offline_time_steps = np.asarray(
            offline_data["time_step"], dtype=np.int64
        ).reshape(-1)
        offline_terminals = np.asarray(
            offline_data["terminals"], dtype=np.bool_
        ).reshape(-1)
        offline_traj_starts = np.asarray(
            offline_data["traj_start_indices"], dtype=np.int64
        ).reshape(-1)
        if not np.array_equal(offline_time_steps, self.time_steps):
            raise ValueError(
                "offline_data time_step metadata is not aligned with the "
                "TPNN history store."
            )
        if not np.array_equal(offline_terminals, self.terminals):
            raise ValueError(
                "offline_data terminals are not aligned with the TPNN "
                "history store."
            )
        if not np.array_equal(
            offline_traj_starts, self.traj_start_indices
        ):
            raise ValueError(
                "offline_data traj_start_indices are not aligned with the "
                "TPNN history store."
            )
        if sample_size < 1:
            return
        sample_size = min(sample_size, n)
        indices = np.unique(
            np.linspace(0, n - 1, sample_size, dtype=np.int64)
        )
        observations = np.asarray(
            offline_data["full_observations"][indices], dtype=np.float32
        )
        pre_actions = np.asarray(
            offline_data["pre_actions"][indices], dtype=np.float32
        )
        actions = np.asarray(
            offline_data["full_actions"][indices], dtype=np.float32
        )
        reconstructed = np.concatenate(
            [observations, pre_actions, actions - pre_actions], axis=-1
        )
        if reconstructed.shape[-1] != self.input_dim:
            raise ValueError(
                f"offline_data produces {reconstructed.shape[-1]} input "
                f"features; the TPNN expects {self.input_dim}."
            )
        if not np.allclose(
            reconstructed,
            self.tokens[indices],
            rtol=0.0,
            atol=1e-6,
            equal_nan=True,
        ):
            raise ValueError(
                "offline_data is not aligned with the TPNN history token bank."
            )
